
server:
  port: 8080

spring:
  # druid 连接池
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/fastdfs?allowMultiQueries=true&autoReconnect=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useUnicode=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


  #  # 热部署
  devtools:
    restart:
      enabled: true #开启
      # 此目录的文件修改后重启
      additional-paths: src/main/java
      exclude: src/main/resources # 此目录的文件修改后不重启

  # 开启后(允许bean重写/覆盖) 事务生效
#  main:
#    allow-bean-definition-overriding: true


# mybatis 配置
#mybatis:
#  mapperLocations: classpath:mapper/*.xml  # mapper 文件位置
#  type-aliases-package: com.fastdfs.entity # 别名
#  config-location: classpath:mybatis/mybatis.cfg.xml  # mybatis配置文件


# =============================== #
#     分布式文件系统FDFS配置       #
# =============================== #
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  host: 39.105.203.152
  port: 80
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:
    - 39.105.203.152:22122